/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed/~/route'
import { Route as AuthedTestImport } from './routes/_authed/~/test'
import { Route as AuthedIdTabImport } from './routes/_authed/~/$id.$tab'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRouteRoute = AuthedRouteImport.update({
  id: '/~',
  path: '/~',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedTestRoute = AuthedTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthedRouteRoute,
} as any)

const AuthedIdTabRoute = AuthedIdTabImport.update({
  id: '/$id/$tab',
  path: '/$id/$tab',
  getParentRoute: () => AuthedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/~': {
      id: '/_authed/~'
      path: '/~'
      fullPath: '/~'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/~/test': {
      id: '/_authed/~/test'
      path: '/test'
      fullPath: '/~/test'
      preLoaderRoute: typeof AuthedTestImport
      parentRoute: typeof AuthedRouteImport
    }
    '/_authed/~/$id/$tab': {
      id: '/_authed/~/$id/$tab'
      path: '/$id/$tab'
      fullPath: '/~/$id/$tab'
      preLoaderRoute: typeof AuthedIdTabImport
      parentRoute: typeof AuthedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteRouteChildren {
  AuthedTestRoute: typeof AuthedTestRoute
  AuthedIdTabRoute: typeof AuthedIdTabRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedTestRoute: AuthedTestRoute,
  AuthedIdTabRoute: AuthedIdTabRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface AuthedRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/~': typeof AuthedRouteRouteWithChildren
  '/~/test': typeof AuthedTestRoute
  '/~/$id/$tab': typeof AuthedIdTabRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/~': typeof AuthedRouteRouteWithChildren
  '/~/test': typeof AuthedTestRoute
  '/~/$id/$tab': typeof AuthedIdTabRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/~': typeof AuthedRouteRouteWithChildren
  '/_authed/~/test': typeof AuthedTestRoute
  '/_authed/~/$id/$tab': typeof AuthedIdTabRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/~' | '/~/test' | '/~/$id/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/~' | '/~/test' | '/~/$id/$tab'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/~'
    | '/_authed/~/test'
    | '/_authed/~/$id/$tab'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/~"
      ]
    },
    "/_authed/~": {
      "filePath": "_authed/~/route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/~/test",
        "/_authed/~/$id/$tab"
      ]
    },
    "/_authed/~/test": {
      "filePath": "_authed/~/test.tsx",
      "parent": "/_authed/~"
    },
    "/_authed/~/$id/$tab": {
      "filePath": "_authed/~/$id.$tab.tsx",
      "parent": "/_authed/~"
    }
  }
}
ROUTE_MANIFEST_END */
